### ISSUE TITLE
"Create Skill" → ”Create Project"

### ISSUE THREAD

**Issue by isabro** [kun432/voiceflow-handson-20190318#2]
下記の画像の箇所です。
![alexa_fb02](https://user-images.githubusercontent.com/45299773/62598291-e6484280-b923-11e9-8045-c75ecfd6a28d.png)

恐らくGoogleでは「スキル」と呼ばないことから、「Project」に表記が変更になっております。
こちらを変更していただければ、と考えます。

**Comment by kun432** [comment]
画面キャプチャを取り直します。

**Comment by itsumonotakumi** [comment]
ありがとうございます！

**Comment by isabro** [comment]
ありがとうございます！
