### ISSUE TITLE
Test 方法が変更されている

### ISSUE THREAD

**Issue by isabro** [kun432/voiceflow-handson-20190318#3]
下記の画像で示されているテストアイコンは無くなっています。
![alexa_fb02](https://user-images.githubusercontent.com/45299773/62598374-24ddfd00-b924-11e9-981d-f1e076e2556e.png)

また、テスト方法も下記のように非常に分かり易くなっていますので、ひとこと触って頂けると説明が非常にラクになります。
![alexa_fb03_correct](https://user-images.githubusercontent.com/45299773/62598442-5ce54000-b924-11e9-840f-5937ce5f5d49.png)

![alexa_fb02_3](https://user-images.githubusercontent.com/45299773/62598424-463ee900-b924-11e9-9f5b-33a7c9c33d7f.png)

**Comment by kun432** [comment]
Voiceflow側のテストは全面的に使わない方針にしようと思っています。というのは、

- そもそもAlexa skills kitを通さないテストにはあまり意味がない。
  - 通常は、ユーザ---echoデバイス---alexa skills kit---voiceflow、となり、必ずalexa skills kitの対話モデルを経由します。ここでどうNRUに判断されSTTされるか？はとても重要です。
  - が、VFのテストは、ユーザ---voiceflowとなり、alexaの対話モデルを経由しません。すなわちユーザの入力をそのまま受け止めてしまいます。これでは実機と異なる動きになってしまいます。
  - ただし、ローカルテストとしての意味合いがなくなるわけではないです。
- 現行のテストツールは日本語の処理に多分に問題があります。そこで期待しない結果になるのはユーザにとっては好ましくありません。

などの理由で、VFのテストツールの信頼性は低いと考えています。テストに関しては開発者コンソールにアップして実施する方向で統一します。

**Comment by itsumonotakumi** [comment]
実態との乖離はともかく、作ったもの流れをクイックに確認するには良いような気がしますけどね。
ただ、ハンズオンの中では紹介しにくいのもわかります。悩ましいですね😩

**Comment by isabro** [comment]
実態との乖離はともかく、作ったもの流れをクイックに確認するには良いような気がしますけどね。
開発者コンソールと行き来するのは負担が大きいので。

ただ、ハンズオンの中では紹介しにくいのもわかります。悩ましいですね😩
軽く流す程度に触れても良いんじゃないかと思います。
