### ISSUE TITLE
変数のアイコンとUIが変更になっている

### ISSUE THREAD

**Issue by isabro** [kun432/voiceflow-handson-20190318#4]
スキルの作成（STEP2）で指定されているアイコンが大きく変わっています。
![alexa_fb04](https://user-images.githubusercontent.com/45299773/62598486-7b4b3b80-b924-11e9-845f-7fbb630b4cdd.png)

**Comment by kun432** [comment]
画面キャプチャを取り直します。

**Comment by itsumonotakumi** [comment]
ありがとうございます！

**Comment by isabro** [comment]
ありがとうございます！
