### ISSUE TITLE
Ifブロックのインターフェース変更

### ISSUE THREAD

**Issue by isabro** [kun432/voiceflow-handson-20190318#5]
些細かもしれませんが、けっこうIfブロックのインターフェースが変わっています。

![alexa_fb05](https://user-images.githubusercontent.com/45299773/62598491-81411c80-b924-11e9-9780-0e43e36f266c.png)

思いのほか、参加者が手間取るようですので、画像の差し替えがあると助かります。

**Comment by kun432** [comment]
ここは正直頭が痛いところです。。。。

- IfをGUIだけでやるのは手数が多すぎて正直キツイと思ってます。
- Expressionという完全手打ちモードがあるのですが、pureなJS実装ではないのと、プログラミング初心者には厳しい感があります。

Interaction blockの話も含めて、「はじめて」の場合にはもっと違うアプローチが必要かなと考えてます。ターゲットをどう設定するか次第ですね。

**Comment by isabro** [comment]
UI自体に問題がある気はします。
ただ、ここでは単純にUIデザインが変更になってるが故の迷いでしたから、画像の差し替えだけで問題ないと思います。

IF自体の「分岐」の概念は、ハンズオンに加えて、丁寧に解説しないとダメでしょうね。ただ、そこは一般的なプログラミング知識であって、ハンズオンの範疇から外して良いと思います。そこの補足は講師の役割だと思いますので、テキストには不要だと思います。
