### ISSUE TITLE
If での NaN 表記

### ISSUE THREAD

**Issue by isabro** [kun432/voiceflow-handson-20190318#6]
恐らくバグだとは思いますが、下記の通り、数字以外だと NaN 表記されてしまうようです。

![alexa_fb06](https://user-images.githubusercontent.com/45299773/62598543-a9c91680-b924-11e9-82eb-b0599e87db8d.png)

動作としては問題ないようですが、解説もしくは回避方法の記載があると助かります。

**Comment by kun432** [comment]
これ公式のFacebookグループでも確か話があって、公式的にはバグではないとのことでした。というのも、

- voiceflowの変数の初期値は0（数値）
- 数値以外だと、文字列・nulll・undefined・bool(true/false）などがある

からではないかなーと思います。If Blockの処理系が結構クセがある（pureなJSではない）ので、致し方ないかなと思ってますが、まあ気にしないような追記があればよいですね。

**Comment by itsumonotakumi** [comment]
なんか文字列がマッチしないように見えて、混乱を招きそうですね。注釈で逃げる感じが良いかもしれませんね。

**Comment by isabro** [comment]
ここはかなり分かりにくいですね。
数字以外がNaNなのは厳しいですね。
「気にするな」という補記があれば、対応できるとは思いますね。
