### ISSUE TITLE
VUIの仕組みの説明スライド

### ISSUE THREAD

**Issue by isabro** [kun432/voiceflow-handson-20190318#7]
「6. スキルの作成（STEP2）」の「VUIの仕組み」説明箇所がけっこう重い印象です。
レクチャーをしようと考えているのですが、何かスライドなどは作られていますでしょうか？
※無ければ作って寄贈しようかと考えます。

**Comment by kun432** [comment]
一番わかり易いのはこれですかねぇ、私も昔Amazonさん主催のハンズオンセミナーで最初に説明を受けたのがこの手の内容でした。ただ、技術者視点だとそんなに違和感ないんですけど、技術専門でない方からするとそうでもないのかもしれませんね。

https://developer.amazon.com/ja/blogs/alexa/post/07377568-2815-4028-8c21-409dd8e84fa2/alexa-training-jp-2nd

あとはこのあたりも近い感じです。

https://www.slideshare.net/junichikawa1/alexa-skills-kit-87985751

個人的には、Interaction Blockを使ったインテントの仕組みを最初からやらずに、Choiceとかを使って動くものを見せたほうがいいのかなと思ってたりします。

**Comment by itsumonotakumi** [comment]
講習会形式のハンズオンだと、後者の一部を拝借する方がプロジェクターで説明しやすいかもしれませんね。
ちょっと試してみますね。

**Comment by isabro** [comment]
講習会形式でやるなら後者のスライドはありがたいですね！
前者もキチンと書いてはあるですが、プロジェクター向きではないので…
ありがとうございます。やってみます！👍

**Comment by kun432** [comment]
インテントとサンプル発話は

https://m.youtube.com/watch?feature=youtu.be&v=C1tir3skpLI

スロットの説明は

https://m.youtube.com/watch?feature=youtu.be&v=PA1KBpoD6jw

合わせて10分ぐらいなのでこれみてもらうのも一つですね
